### ISSUE TITLE
Add step to run smoke tests

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-pipeline#119]
Once the step to build a kernel image is complete, the next part is to run `kvm-xfstests` with the `smoke` set of tests.  This is a relatively small set which can take around 15min to complete on a decent machine.  It's a good compromise to have some useful coverage without running the full set of tests which would take many hours.

During development, it's also possible to hard-code a couple of test names to get results much quicker rather than the whole `smoke` set.

- [x] Step added to add another call `kvm-xfstests` to run the `smoke` tests
- [x] Verified manually in the log output that the tests were run as expected
- [x] Overall status reported to the API, still with a single `fstests` node

**Comment by alexandrasp** [comment]
- I am investigating how to access the VM and get the result.xml during the run time. 
- Manually I am already able to see the tests running, so when the tests finish I can join the VM and see the results file.

**Comment by gctucker** [comment]
I don't think it's necessary to get the XML file out of the VM, checking the output is enough for now to know the tests were run as expected.  We'll see the details of the logs when parsing the XML results.
