### ISSUE TITLE
Empty test report generation on staging

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-pipeline#168]
### Issue:

Empty test reports are being generated on staging.

Test report logs:
```
today at 05:36:2711/02/2022 12:06:27 AM UTC [INFO] Listening for completed nodes
today at 05:36:2711/02/2022 12:06:27 AM UTC [INFO] Press Ctrl-C to stop.
today at 05:49:23kernelci/staging-mainline None: 0 runs 0 failures
today at 05:49:23
today at 05:49:23Summary
today at 05:49:23=======
today at 05:49:23
today at 05:49:23Tree:     kernelci
today at 05:49:23Branch:   staging-mainline
today at 05:49:23Describe: None
today at 05:49:23URL:      https://github.com/kernelci/linux.git
today at 05:49:23SHA1:     f9b9078b2642e6503faadfc094703a339d98f323
today at 05:49:23
today at 05:49:23Name            | Result   | Total    | Failures
today at 05:49:23----------------+----------+----------+---------
today at 05:49:23
today at 05:49:23
today at 05:49:23Failing tests
today at 05:49:23=============
```

Notifier logs:
```
today at 05:36:2711/02/2022 12:06:27 AM UTC [INFO] Time                        Commit        Node Id                   State      Result    Name
today at 05:49:2211/02/2022 12:19:22 AM UTC [INFO] 2022-11-02 00:19:22.863063  f9b9078b2642  636066098f94e20c6826b0b3  Done       Incomplete  checkout
```

### Root Cause:

We have introduced various node results including `pass`, `fail`, `skip`, and `incomplete`.
When tarball creation starts, `checkout` node state will be set to `running`.
In case of `checkout` node times out while still in the `running` state, the node result will be set to `incomplete` and state to `done`.
Since the `checkout` node state is changed to `done`, test report will be generated even if the node is incomplete.

### Possible fixes:

Need to verify node result before creating test reports in `test_report`.

**Comment by gctucker** [comment]
OK, I think a better fix for this would be to send the report but mention there was a failure in the checkout node.

**Comment by JenySadadia** [comment]
This is a case of time-out rather than failure.
I think we wanted to mention only failures and regressions in test reports and left timed-out nodes from it.
We can consider reporting timed out nodes when we have some error information bound to the node to make sure it is a failure.

**Comment by gctucker** [comment]
Reporting the fact that a kernel revision failed to go through the pipeline is useful information, if people are expected results at least they know there won't be any because something was broken.  It should be reported as a pipeline infrastructure error I guess, that's not the same as kernel errors.

**Comment by JenySadadia** [comment]
Makes sense.
I have started working on it.

**Comment by JenySadadia** [comment]
> Reporting the fact that a kernel revision failed to go through the pipeline is useful information, if people are expected results at least they know there won't be any because something was broken. It should be reported as a pipeline infrastructure error I guess, that's not the same as kernel errors.

Please take a look at https://github.com/kernelci/kernelci-pipeline/pull/169#issuecomment-1313438178
