### ISSUE TITLE
Introduce Job class

### ISSUE THREAD

**Issue by mgalka** [kernelci/kernelci-pipeline#183]
At the moment the `Runner` service is responsible for defining, creating and running jobs. Job definitions should be decoupled from the running logic.

Job objects should be extracted from the current Runner service.  The base `Job` class should be introduced to unify structure and common functionality of the jobs. The Runner service should be responsible only for instantiating and running jobs which derive from the `Job` class. 

 - [ ]  Job class created
 - [ ]  Job related code refactored and moved into Job class derivatives
 - [ ]  Runner service logic adjusted to run Job class instances

**Comment by gctucker** [comment]
I believe we also need to reshape the Lab class into something like Runtime and resolve the difference between the template arguments passed to the LAVA job generators and the new runtime templates using shell or k8s.  I think the Runtime class would have implementations that provide the template data to the job generation, basically we could have some test templates that only rely on common variables and the base runtime templates would be tied to the implementations to pass the relevant things as required.  The input data would still be the same, such as the incoming node which the job to be generated depended upon (sorry if that's a bit abstract...).  That probably also means we'll need to get the nodes dependency implementation done before sorting out the Runtime implementations.  In practice I guess we'll have to do things in incremental steps with some incomplete features and shortcuts or hard-coded things to get the whole thing bootstrapped.  Maybe some design / documentation would be nice to have to keep all the efforts well coordinated.  Let me know if you need some help with that.
