### ISSUE TITLE
LAVA Runtime initial support

### ISSUE THREAD

**Issue by mgalka** [kernelci/kernelci-pipeline#185]
LAVA is the predominant runtime environment for KernelCI.  KernelCI Pipeline should be capable of generating LAVA job definitions as well as submitting them to LAVA labs and collecting the results.

Appropriate job and runtime environment definitions need need to be introduced as well as logic capable of submitting test jobs to LAVA and collecting results.

- [x] LAVA templates added in `config/runtime` at least for one type of tests (e.g. baseline on QEMU x86)
- [x] LAVA runtime environment created to make use of it in `kernelci.runtime`
- [x] verified locally with `kci job` commands
- [x] verified on staging with `runner` service
~~kernelci-pipeline capable of collecting results from LAVA test jobs~~ Moving this to a separate issue

**Comment by gctucker** [comment]
That's great.  We just need to make sure we cover adding support for builds first, as for LAVA boards we need build artifacts (unlike KUnit running in k8s and fstests running in GCE with their own builds under the hood).

**Comment by gctucker** [comment]
The initial LAVA Runtime implementation is there so we can now close this issue.  Some follow-up improvements will be needed in order to run all the possible jobs with changes in the YAML config, scheduler and LAVA job templates but these are outside the scope of this issue.
