### ISSUE TITLE
Introduce API versioning

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-pipeline#197]
Since the models of API are evolving gradually with the requirements, it is time to introduce versioning to have model fields, and endpoints specific to the API version.

e.g. Node state values can be revised over a period of time. Hence, it is a good idea to bind it with a specific API version.
```
class StateValues(enum.Enum):
    """Enumeration to declare values to be used for Node.state"""

    RUNNING = 'running'
    AVAILABLE = 'available'
    CLOSING = 'closing'
    DONE = 'done'
```

It is worth taking a look at https://pypi.org/project/fastapi-versioning/ to achieve this.

**Comment by JenySadadia** [comment]
By mistake, I created API specific issue here.
Opened https://github.com/kernelci/kernelci-api/issues/208 and closing this one.

**Comment by gctucker** [comment]
FYI there's also the "Transfer issue" feature on GitHub for that.

**Comment by JenySadadia** [comment]
Oh, I wasn't aware of that.
Thanks for the information.
Noted.
