### ISSUE TITLE
Test Report: not able to create SMTP connection

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-pipeline#273]
Test report crashes on staging with the below error logs:
```
today at 11:58:0706/05/2023 06:28:07 AM UTC [ERROR] Traceback (most recent call last):
today at 11:58:07  File "/home/kernelci/pipeline/base.py", line 69, in run
today at 11:58:07    status = self._run(context)
today at 11:58:07  File "/home/kernelci/pipeline/test_report.py", line 131, in _run
today at 11:58:07    self._send_report(subject, content)
today at 11:58:07  File "/home/kernelci/pipeline/test_report.py", line 105, in _send_report
today at 11:58:07    self._email_sender.create_and_send_email(subject, content)
today at 11:58:07  File "/home/kernelci/pipeline/kernelci_pipeline/email_sender.py", line 65, in create_and_send_email
today at 11:58:07    self._send_email(email_msg)
today at 11:58:07  File "/home/kernelci/pipeline/kernelci_pipeline/email_sender.py", line 55, in _send_email
today at 11:58:07    smtp = self._smtp_connect()
today at 11:58:07  File "/home/kernelci/pipeline/kernelci_pipeline/email_sender.py", line 32, in _smtp_connect
today at 11:58:07    smtp = smtplib.SMTP(self._smtp_host, self._smtp_port)
today at 11:58:07  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__
today at 11:58:07    (code, msg) = self.connect(host, port)
today at 11:58:07  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect
today at 11:58:07    self.sock = self._get_socket(host, port, self.timeout)
today at 11:58:07  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket
today at 11:58:07    return socket.create_connection((host, port), timeout,
today at 11:58:07  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
today at 11:58:07    raise err
today at 11:58:07  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
today at 11:58:07    sock.connect(sa)
today at 11:58:07OSError: [Errno 99] Cannot assign requested address
today at 11:58:07
today at 12:01:42Container stopped
```
Verified entries in `kernelci-pipeline/.env` and user settings file on staging. This could be some configuration issue on the server after it got moved to a new Azure subscription.

**Comment by JenySadadia** [comment]
I tested locally and used staging configurations of the test report to debug it. It worked fine locally.

**Comment by JenySadadia** [comment]
I tried to use SMTP port `587` on staging. It didn't work either.
I also tried to check if port 465 or 587 is in use but seems like no service is using it.
Maybe something is blocking the port on the VM? Could you please take a look at it? @VinceHillier

**Comment by gctucker** [comment]
How come `kernelci-backend` is able to send emails from the same VM though?

Ah I think this is an IPv6 issue with the Docker bridge service.  The `kernelci-backend` service is running natively on the host in a Python environment, not Docker.  So that's the critical bit of difference.  I'm pretty sure it's something we "solved" a while ago on the other VM and somehow it got lost in the move.  It's a classic issue though, there should be something on StackOverflow (or the real manuals) to avoid this issue.  Or maybe it's an issue with the network configuration in Azure for the new VM.

**Comment by JenySadadia** [comment]
> How come `kernelci-backend` is able to send emails from the same VM though?
> 
> Ah I think this is an IPv6 issue with the Docker bridge network interface. The `kernelci-backend` service is running natively on the host in a Python environment, not Docker. So that's the critical bit of difference. I'm pretty sure it's something we "solved" a while ago on the other VM and somehow it got lost in the move. It's a classic issue though, there should be something on StackOverflow (or the real manuals) to avoid this issue. Or maybe it's an issue with the network configuration in Azure for the new VM.

But it worked locally even with the docker environment. Seems to be the network config issue of the VM. Could you please give me some pointers on how to debug that?

**Comment by gctucker** [comment]
I don't really know, I guess to start with you could try to reproduce it by hand by opening an interactive shell in the `notifier` container on staging and connecting to the SMTP server with `nc`.  You can run a container as `root` to install `nc` with `apt` if needed.

**Comment by JenySadadia** [comment]
> I don't really know, I guess to start with you could try to reproduce it by hand by opening an interactive shell in the `notifier` container on staging and connecting to the SMTP server with `nc`. You can run a container as `root` to install `nc` with `apt` if needed.

Okay. Thanks.

**Comment by gctucker** [comment]
I think it actually may just boil down to this: https://github.com/kernelci/kernelci-pipeline/pull/287

**Comment by gctucker** [comment]
Looks like this one worked yesterday?

```
[STAGING] kernelci/staging-mainline staging-mainline-20230724.0: 0 runs 0 failures

Summary
=======

Tree:     kernelci
Branch:   staging-mainline
Describe: staging-mainline-20230724.0
URL:      https://github.com/kernelci/linux.git
SHA1:     c84125cf4830cc3ff5e622237599d3afc33cfafb
```

**Comment by JenySadadia** [comment]
> Looks like this one worked yesterday?
> 
> ```
> [STAGING] kernelci/staging-mainline staging-mainline-20230724.0: 0 runs 0 failures
> 
> Summary
> =======
> 
> Tree:     kernelci
> Branch:   staging-mainline
> Describe: staging-mainline-20230724.0
> URL:      https://github.com/kernelci/linux.git
> SHA1:     c84125cf4830cc3ff5e622237599d3afc33cfafb
> ```

That I sent from local run.

**Comment by gctucker** [comment]
Maybe add something to the email subject next time to make it clear it's yours.  But that's a detail.  I think the issue was about `KCI_SETTINGS`, let's see if the next staging runs have more success.

**Comment by gctucker** [comment]
Well the `OSError: [Errno 99] Cannot assign requested address` issue is still there.  That does sound like a network setup issue, and probably there was also the `KCI_SETTINGS` issue but it never got that far due to the first issue.

**Comment by JenySadadia** [comment]
> I think the issue was about `KCI_SETTINGS`, let's see if the next staging runs have more success.

That won't make any difference. As it worked fine with even `SETTINGS` locally. It must be some networking issue.

**Comment by gctucker** [comment]
Yes, that's what I meant.  I think the settings env variable rename would then have been an issue but there's also a networking issue anyway.  Have you tried to reproduce it manually?

**Comment by JenySadadia** [comment]
> Yes, that's what I meant. I think the settings env variable rename would then have been an issue but there's also a networking issue anyway. Have you tried to reproduce it manually?

Not yet. I'll try it soon.

**Comment by JenySadadia** [comment]
I tried manually from `api` container on staging:
```
root@23cdeaf3732a:/home/kernelci# nc -vz smtp.gmail.com 465
Connection to smtp.gmail.com (142.251.2.109) 465 port [tcp/submissions] succeeded!
root@23cdeaf3732a:/home/kernelci# nc -vz smtp.gmail.com 587
Connection to smtp.gmail.com (142.250.141.109) 587 port [tcp/submission] succeeded!
```

**Comment by gctucker** [comment]
OK, maybe try again in the container running the email report service?

**Comment by JenySadadia** [comment]
Hello,
See below results from test_report container:
```
root@86eba74f8de6:/home/kernelci# nc -vz smtp.gmail.com 465
Connection to smtp.gmail.com (74.125.137.109) 465 port [tcp/submissions] succeeded!
root@86eba74f8de6:/home/kernelci# nc -vz smtp.gmail.com 587
Connection to smtp.gmail.com (142.250.101.109) 587 port [tcp/submission] succeeded!
```

For the experiment, I added the below lines to `email_sender` module and tried to send an email from the container directly:
```
if __name__=="__main__":
    es = EmailSender("smtp.gmail.com", 465, "bot@kernelci.org", "jeny.sadadia@collabora.com")
    es.create_and_send_email("Test", "test email")
```
It worked and I received the test email ! Port `587` also worked fine. This is weird. Taking another look.

**Comment by JenySadadia** [comment]
Found the issue.


When I added the below lines to `TesReport` constructor:
```
print("[DEBUG] args.smtp_port", args.smtp_port)
es = EmailSender(args.smtp_host, args.smtp_port, "bot@kernelci.org", "jeny.sadadia@collabora.com")
es.create_and_send_email("Test", "test email")

```

I receive below logs and the connection errors:
```
kernelci-pipeline-test_report | [DEBUG] args.smtp_port 25
```
So,  `smtp_port` value is set to the default value i.e. `25` instead of `465` from the settings file. And that is causing the issue.
I wonder why It doesn't reproduce locally.
