### ISSUE TITLE
Fix list of results in email report summary

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-pipeline#279]
The current email reports look like this:
```
On 30/05/2023 09:20, staging.kernelci.org bot wrote:
> [STAGING] mainline/master v6.4-rc4-31-g8b817fded42d: 4 runs 0 failures
> 
> Summary
> =======
> 
> Tree:     mainline
> Branch:   master
> Describe: v6.4-rc4-31-g8b817fded42d
> URL:      https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
> SHA1:     8b817fded42d8fe3a0eb47b1149d907851a3c942
> Name            | Result   | Total    | Failures
> ----------------+----------+----------+---------
> kver            | pass     |        1 |        0
> kunit           | pass     |        7 |        0
> kunit-x86_64    | pass     |      723 |        2
> kbuild-gcc-10-x86 | pass     |       11 |        0
> 
> 
> Failing tests
> =============
> 
> kunit-x86_64
> ------------
> 
> * exec.input_core.input_test_match_device_id
> * exec.input_core.input_test_match_device_id
```
However, `kbuild-gcc-10-x86` doesn't actually have 11 cases.  This number includes the child nodes, in this case `baseline-x86`.  The report should be showing `baseline-x86` results separately.  It can do this using the `group` attribute to know which nodes belong to the same test or build.

- [ ] Report updated to show all grouped results
- [ ] Tested locally
- [ ] Tested on staging

**Comment by JenySadadia** [comment]
Hello @gctucker 
I started analyzing the issue and have a question.
`baseline-x86` is specified as a separate job in `pipeline.yaml`. How come it has parent as node `kbuild-gcc-10-x86`?
`checkout` node should be its parent instead.
For instance https://staging.kernelci.org:9000/latest/node/64b52d72b5b4a9b8c05e0b69 is a `baseline` job node. The node has the parent as https://staging.kernelci.org:9000/latest/node/64b52bcdb5b4a9b8c05e0878.

**Comment by JenySadadia** [comment]
Okay. Found an explaination.
Because if depends on `kbuild` job.
```
- job: baseline-x86
    event:
      channel: node
      name: kbuild-gcc-10-x86
      result: pass
    runtime:
      type: lava
    platforms:
      - qemu-x86
```

**Comment by gctucker** [comment]
Yes it's normal for baseline to have kbuild as a parent.  What's broken or missing is the email reporting logic to look for distinct jobs (or "groups" as they're called now) to add in the report table rather than just "first-gen" child nodes of checkout.
