### ISSUE TITLE
Replace _print with logging

### ISSUE THREAD

**Issue by mgalka** [kernelci/kernelci-pipeline#44]
In some places in `kernelci-pipeline` classes have `_print()` and/or `_info()` methods. They've been used for displaying output of the scripts.
E.g.

- https://github.com/kernelci/kernelci-pipeline/blob/19c1a7aa8b39c6d56c8260afc8cb6b033c676e51/src/tarball.py#L37
- https://github.com/kernelci/kernelci-pipeline/blob/19c1a7aa8b39c6d56c8260afc8cb6b033c676e51/src/test_report.py#L51

The methods should be removed from the classes and replaced with Python's built-in `logging` module with appropriate log levels set up. 
There should be preferably a separate python module that would provide a logger object which can be used by all `kernelci-pipeline` scripts.

- [ ] Create logger and configure it for kernelci-pipeline
- [ ] Use logger in the scripts where `self._print()` and `self._info()` methods are used
- [ ] remove old logging methods i.e. `_print`, `_info`

**Comment by gctucker** [comment]
How do you control flushing of stdout with the `logging` module?

**Comment by JenySadadia** [comment]
> How do you control flushing of stdout with the `logging` module?

We can define console handlers for stdout. We can also use file handlers if we want to use log files.

**Comment by gctucker** [comment]
OK so basically a custom implementation but in a separate module.  I guess it might just not be possible with the `logging` module to have several messages printed without flushing the stdout buffer and then flushing it later.  But I don't think that's a big issue.

**Comment by JenySadadia** [comment]
PRs have been merged.
