### ISSUE TITLE
Enable ARCH=um - UM Linux compiling tests - for Android Common Kernels

### ISSUE THREAD

**Issue by helen-fornazier** [kernelci/kernelci-pipeline#483]
Reference: https://lore.kernel.org/kernelci/CAHRSSEwe1z7pajTmLNJRHbBv1Ghnz-siAyw4CU5kraN3_hLqpg@mail.gmail.com/T/#t

It was requested to add UML compiling tests `ARCH=um SUBARCH=x86_64` to kernelci for Android Common Kernels

Add them into the new system and check the best way to report errors from it

**Comment by pawiecz** [comment]
Here's a list of steps to enable setting env variables for the builds in the new system:

1. Start by making them an argument to [`_build*`](https://github.com/kernelci/kernelci-core/blob/6572f1c403506d4ce2c1117167cf86054adb1db3/kernelci/kbuild.py#L526) functions in the [kernel build abstraction package](https://github.com/kernelci/kernelci-core/blob/main/kernelci/kbuild.py)
2. Once it ^ accepts parameters, adjust [kbuild job template](https://github.com/kernelci/kernelci-pipeline/blob/main/config/runtime/kbuild.jinja2) to pass these parameters (as `KBUILD_PARAMS`) to executed job
3. When ^ job template is adjusted, set env vars in your new kbuild job definition; see [example gcc-10-arm64 definition](https://github.com/kernelci/kernelci-pipeline/blob/e2bcc7dc6ae24df321aaf360805ee360b797b369/config/pipeline.yaml#L183) and its neighbors

**Comment by musamaanjum** [comment]
@helen-fornazier All the Android builds and baseline tests on arm/arm64 have been enabled. Is there anything else remaining for this issue? The PR, https://github.com/kernelci/kernelci-pipeline/pull/528 seems outdated.
