### ISSUE TITLE
Handle incomplete/fail checkout

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-pipeline#554]
Update checkout node with appropriate state and result when code checkout fails or node times out while running checkout.

- [ ] Update checkout failure in `tarball.py`
- [ ] Update timed-out checkout in `timeout.py`

**Comment by nuclearcat** [comment]
I suggest also on checkout failure to clean "cache directory" of git with sources, like it was done on another failure, because likely reason is corruption, this will help it to recover at least on next kernel.

**Comment by JenySadadia** [comment]
> I suggest also on checkout failure to clean "cache directory" of git with sources, like it was done on another failure, because likely reason is corruption, this will help it to recover at least on next kernel.

The cleanup logic is already in place https://github.com/kernelci/kernelci-pipeline/blob/main/src/tarball.py#L78.
