### ISSUE TITLE
Manual for adding new tests

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-pipeline#573]
We need a manual/guide describing instructions for adding new tests to the new KernelCI system.
This would save time spent on investigating the workflow by new developers while adding new tests.

- [ ] Add documentation
- [ ] Deploy it on [kernelci.org/docs](kernelci.org/docs) (Maybe a new page under https://kernelci.org/docs/api/?)

**Comment by pawiecz** [comment]
Part of this task will be to verify template rendering for added tests. Very quick overview of rendering process (using data from pipeline configuration) has been posted in https://github.com/kernelci/kernelci-project/issues/358#issuecomment-2112430605 together with an example of `kci job generate` tool usage in https://github.com/kernelci/kernelci-project/issues/358#issuecomment-2136078333.

This resulted in two PRs: https://github.com/kernelci/kernelci-core/pull/2565 and https://github.com/kernelci/kernelci-pipeline/pull/623 (which could potentially be used as reference later). The latter also includes author's verification process https://github.com/kernelci/kernelci-pipeline/pull/623#issuecomment-2139610589
