### ISSUE TITLE
Maestro-KCIDB bridge service migration to production

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-pipeline#664]
As KCIDB bridge service reached maturity, to make results more reliable we need to migrate it to Maestro production environment.
Following steps planned:

1.
- Disable KCIDB bridge service in Maestro staging environment
- Enable KCIDB bridge service in Maestro production environment to submit data to playground KCIDB
- Verify that data is submitted correctly to playground KCIDB
2.
- Disable KCIDB bridge service in Maestro staging environment
- Enable KCIDB bridge service in Maestro production environment to submit data to production KCIDB
- Verify that data is submitted correctly to production KCIDB
3.
- Enable KCIDB bridge service in Maestro staging environment to submit data to playground KCIDB
- Verify that data is submitted correctly to playground KCIDB

We need to keep step 1 short as possible, if possible to do it in one day.

**Comment by JenySadadia** [comment]
We don't need to disable bridge service on staging environment.
The service running on production will submit data to KCIDB's production and will be distinguishable on the dashboard.
