### ISSUE TITLE
Implement retry logic for lab tests

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-pipeline#665]
In situations of unreliable test results kernel maintainers often need to rerun the tests to ensure the results are correct. This can be due to a variety of reasons such as flaky tests, network issues, or other transient failures.
Previous attempts to implement retry logic have been unsuccessful due to the way the event logic implemented. Even if we spoof pubsub event and retry build node, the event logic will fetch
nodeid with real data (different from spoofed) and will fail to trigger test event.
This time we will put more effort to implement retry logic for lab tests.
Further information will be posted as follow-up comments.

**Comment by JenySadadia** [comment]
Hello,
There was already an issue created for it by @hardboprobot 
https://github.com/kernelci/kernelci-api/issues/509

**Comment by nuclearcat** [comment]
OK i will migrate this issue as comment there with details according to initial issue
