### ISSUE TITLE
Builds failing due to missing topology files

### ISSUE THREAD

**Issue by crazoes** [kernelci/kernelci-pipeline#726]
This issue is something that was overlooked in the legacy system and unfortunately, we have started to see the same problem in the new KernelCI.

Various builds are failing because of the missing topology file which leads to incorrect results.
Logs :- 
```
  UPD     drivers/base/firmware_loader/builtin/mediatek/sof-tplg/sof-mt8186.tplg.gen.S
make[6]: *** No rule to make target '/tmp/kci/firmware/mediatek/sof-tplg/sof-mt8195-mt6359-rt1019-rt5682-dts.tplg', needed by 'drivers/base/firmware_loader/builtin/mediatek/sof-tplg/sof-mt8195-mt6359-rt1019-rt5682-dts.tplg.gen.o'.  Stop.
make[6]: *** Waiting for unfinished jobs....
  UPD     drivers/base/firmware_loader/builtin/mediatek/sof-tplg/sof-mt8195-mt6359-rt1019-rt5682-dts.tplg.gen.S
make[5]: *** [scripts/Makefile.build:480: drivers/base/firmware_loader/builtin] Error 2
make[4]: *** [scripts/Makefile.build:480: drivers/base/firmware_loader] Error 2
make[3]: *** [scripts/Makefile.build:480: drivers/base] Error 2
``` 

Following is one of the example :-

![Image](https://github.com/user-attachments/assets/bb11e000-53d3-49f5-8428-06a6e27b5e7d)

I'm sure this issue is happening in other branches and trees as well. We need to fix them asap.

Link to some results where we see build failing due to this issue :- https://fresh-kcidb-grafana-m6io3uhhiq-uc.a.run.app/d/OKXc44EIz/wip3a-koike?orgId=1&var-origin=All&var-tree=stable-rc&var-branch=linux-6.6.y&var-test_path_regex=boot&var-platform=%25&var-config=%25&var-datasource=default

cc @padovan @nuclearcat @musamaanjum @pawiecz @JenySadadia @laura-nao

**Comment by musamaanjum** [comment]
The [arm64-chromebook fragment](https://github.com/kernelci/kernelci-core/blob/main/config/core/build-configs.yaml#L371) mentions the `.tplg` files. Maybe the builds which don't use this fragment get failed.

**Comment by nfraprado** [comment]
That firmware was removed from linux-firmware in this patch: https://lore.kernel.org/all/20240719022132.30990-1-xiangzhi.tang@mediatek.com/ . I've sent a question there to know if another kernel change will soon be sent to allow another firmware to be used instead: https://lore.kernel.org/all/e8e66f8f-4238-4d8a-ad20-32bc4cb1dbb1@notapiano

In the mean time we should consider audio functionality for MT8195 Tomato broken and drop the firmware from the config, which I've done here: https://github.com/kernelci/kernelci-core/pull/2623
