### ISSUE TITLE
Discrapency in data on Grafana vs result-summary for stable-rt

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-pipeline#745]
Maintainers are already using Grafana dashboard. There was a report that preempt_rt config builds are missing (https://github.com/kernelci/kernelci-core/pull/2397#issuecomment-2272789692). I've investigated and found out that the builds data is visible in results obtained from result-summary.

https://grafana.kernelci.org/d/OKXc44EIz/home?orgId=1&var-origin=maestro&var-tree=stable-rt&var-branch=All&var-test_path_regex=%25&var-platform=%25&var-config=%25&var-datasource=cdmoe4lcafu2od

I'll attach the results file from result-summary below in the comments as it isn't attached here.

The discrepancies are as follows:
1. The date is different on both. Grafana shows 2024-08-07 while result-summary shows 2024-08-06.
2. The `preempt_rt` jobs aren't present on Grafana and `preempt_rt` isn't present on config column. Probably `preempt_rt` jobs are missing.
3. Grafana only shows reuslts for v6.6.44-rt39 branch. Other 2-3 branches are missing.

cc: @nuclearcat @padovan

**Comment by musamaanjum** [comment]
[stable-rt.html.log](https://github.com/user-attachments/files/16520769/stable-rt.html.log)

@helen-fornazier I'm unable to assign this issue to you. Please have a look at what is causing the discrapency.

**Comment by helen-fornazier** [comment]
I see all these branches for stable-rt

![image](https://github.com/user-attachments/assets/af1a98b5-0475-46cd-bfe0-7590b43397a1)

what is missing?


But indeed, I wans't able to find node `66abc518e49a7366b292a076` in KCIDB for instance (which is present in the report you sent). @JenySadadia could you check please? 


Also, shouldn't these node_timeouts be a MISS ?

![image](https://github.com/user-attachments/assets/44414195-a0e9-4230-a91d-fc812f2d2890)

**Comment by helen-fornazier** [comment]
about the MISS, I just noticed, these are build errors, we need this https://github.com/kernelci/kcidb-io/issues/82

**Comment by musamaanjum** [comment]
> But indeed, I wans't able to find node 66abc518e49a7366b292a076 in KCIDB for instance (which is present in the report you sent). @JenySadadia could you check please?

@helen-fornazier @JenySadadia This is my only concern at this time. The data should have been the same at both places.

**Comment by JenySadadia** [comment]
I checked staging logs.
Maestro didn't submit this entry. Then how did it reach to the new dashboard?
Is that any other source submitting maestro data to it? @helen-fornazier

**Comment by helen-fornazier** [comment]
Let me clarify things:

about 66abc518e49a7366b292a076:
- it is not present in the grafana dashboard
- but it is present in the [stable-rt.html.log](https://github.com/user-attachments/files/16520769/stable-rt.html.log) sent by @musamaanjum as you can see in the picture below
- you can access it at https://staging.kernelci.org:9000/viewer?node_id=66abc518e49a7366b292a076 (see picture 2)

So the question is: **why it is not in KCIDB ?** , why maestro didn't submit it ? (cc @JenySadadia )

![image](https://github.com/user-attachments/assets/48941481-6ea3-469c-849c-aa95af2f0740)

![image](https://github.com/user-attachments/assets/9ce8f55f-334e-4425-a9ba-e9d1b5a2b2a8)

**Comment by JenySadadia** [comment]
Hello @helen-fornazier @musamaanjum 

I analyzed the staging logs and found the root cause.
From the logs, kcidb bridge service crashed on `08/01/2024 06:17:29 PM UTC` and restarted on `08/02/2024 12:16:55 AM UTC`.

The node https://staging.kernelci.org:9000/viewer?node_id=66abc518e49a7366b292a076 was updated at `2024-08-01 08:08:57 PM UTC`.
That's why we lost the `updated` event from API as bridge service was not running at that time. Hence, KCIDB submission is missing for the node.

This issue has been partially taken care of by a patch that auto-restarts all the pipeline services after a crash.
The patch has been merged and deployed on 2nd Aug.

**Comment by musamaanjum** [comment]
I've checked stable-rt. There hasn't been any update for 8 days. Let's wait to see if we get correct results and coherent results on Grafana on the next run.

**Comment by crazoes** [comment]
@musamaanjum @helen-fornazier @JenySadadia can we close this task if it has been resolved?

**Comment by musamaanjum** [comment]
Grafana has been working fine from quite some time. Closing the ticket.
