### ISSUE TITLE
Separate the kselftest build from the kernel build

### ISSUE THREAD

**Issue by crazoes** [kernelci/kernelci-pipeline#767]
Currently we are seeing that the complete kernel build is marked as failed even though the kernel build worked fine and instead it was kselftest build which failure due to errors.
Since we are now sending automated reports for stable-rc, it is important to separate these to avoid any false positives and extra efforts in checking the build failures.
cc @nuclearcat @a-wai @padovan @pawiecz @JenySadadia

**Comment by nuclearcat** [comment]
Can you give me examples where kselftest failed build?
I verified code, it looks like kselftest should not cause build failure even in old code.
I added also separate kselftest build node, to indicate build failure https://github.com/kernelci/kernelci-core/pull/2646

**Comment by crazoes** [comment]
@nuclearcat here is an example where you'll see that the build is marked as failed due to kselftest build failures :-

https://grafana.kernelci.org/d/build/build?orgId=1&var-datasource=default&var-build_architecture=mips&var-build_config_name=32r2el_defconfig&var-id=maestro%3A66be0299dd8611e6bb46bbbf&from=1724667263817&to=1724753663817

**Comment by nuclearcat** [comment]
That node have pass status: https://kernelci-api.westus3.cloudapp.azure.com/viewer?node_id=66be0299dd8611e6bb46bbbf
Probably it is old bug that was related to node timeout, fixed by @JenySadadia

**Comment by crazoes** [comment]
I verified the latest results and could confirm that the kselftest and kernel build results are now separated.
Closing this issue.
