### ISSUE TITLE
Enable the remaining trees from legacy into new KernelCI

### ISSUE THREAD

**Issue by musamaanjum** [kernelci/kernelci-pipeline#776]
Enable the remaining trees. Some trees may already be enabled, but some branches or configurations may be missing. Add that missing configuration as well.

- agross
- khilman
- kselftest
- mainline
- media
- mediatek
- next
- riscv
- rust-for-linux

closes https://github.com/kernelci/kernelci-project/issues/403
PR: https://github.com/kernelci/kernelci-pipeline/pull/779

**Comment by musamaanjum** [comment]
Are we tracking the rustc support in the new KernelCI somewhere? I've not seen any reference to it in the new KernelCI. We may have to add the support.

**Comment by nuclearcat** [comment]
media/master and fixes is enough for now.
Please open issue, that we need to enable Rust in new kernel. Most likely it will be done after legacy is shut, we dont have resources to enable it now.

**Comment by musamaanjum** [comment]
> Please open issue, that we need to enable Rust in new KernelCI. Most likely it will be done after legacy is shut, we dont have resources to enable it now.

Opened: https://github.com/kernelci/kernelci-project/issues/441
