### ISSUE TITLE
Create LAVA labs mapping for viewer and kcidb bridge in config file

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-pipeline#910]
https://github.com/kernelci/kernelci-pipeline/pull/898#pullrequestreview-2458015874
We must try to avoid hardcoding such values in source code.

**Comment by JenySadadia** [comment]
Yes, we need to have dynamic mapping at some point.
One way to achieve it is to read `runtimes` from `pipeline.yaml` and create a `dict` dynamically. All the runtimes can be fetched with `configs['runtimes']` in `KCIDBBridge` class just like we are fetching `jobs` and `platforms` atm.
